### ISSUE TITLE
Docs: Unsure what is meant by remote state Q & A

### ISSUE THREAD

**Issue by brandoconnor** [hootsuite/atlantis#154]
Looking for explanation as this has me confused:

> 
> **Q: Does Atlantis affect Terraform remote state?**
> A: No. Atlantis does not interfere with Terraform remote state in anyway.
> 

Remote state **must** be at least read for terraform to generate a plan. Further, if `terraform apply` is done on PR merge, if state (remote or otherwise) isn't updated during that apply, how would terraform know that change ever happened for future runs? I don't think this question/answer is conveying the author's meaning.

Help me understand and hopefully we can update the docs to reflect what's meant.

**Comment by lkysow** [comment]
Yes, you're right that this should be clearer.

- Atlantis doesn't affect remote state outside of the terraform commands it
runs. So when you run atlantis plan or apply it does affect remote state
because in the background it's actually running terraform plan and apply.
We just meant that Atlantis isn't doing anything special.
- Just a small classification, we don't run apply on merge, we rely on the
user typing atlantis apply

**Comment by brandoconnor** [comment]
Ahh, I understand and thanks for the clarification.

So, though terraform still affects state (remote or otherwise) change normally, Atlantis itself does not touch state outside of those cycles. Atlantis is simply running terraform normally through the medium of PR comments and commenting back. Let me see if I can't summarize that in the README.
