### ISSUE TITLE
Where are .tfstate and .tfstate.backup stored?

### ISSUE THREAD

**Issue by minghsieh-prenetics** [hootsuite/atlantis#207]
Hi,

I am testing on atlantis but unfortunately I messed up the whole region. How do I call `terraform destroy` in atlantis? Or, if I have to call that from the host machine, where are .tfstate and .tfstate.backup stored?

Currently I have to open another region aws console, check which resources should not exist and delete them all.

**Comment by lkysow** [comment]
@minghsieh-prenetics are you using local state? If you're using remote state then your state will be wherever it's configured to be. Atlantis should only be used with remote state because otherwise your state needs to be checked into the repo which Atlantis can't do for you.

See https://www.terraform.io/docs/state/remote.html

To answer your question, Atlantis checks out your repo to `~/.atlantis/repos/{owner}/{repo}/{pullRequestNum}/{workspace}`. If you're using local state then the `.tfstate` files should be in there.

**Comment by minghsieh-prenetics** [comment]
Well, I just try again with standard `./atlantis bootstrap` cmd. It turns out the terraform state stored in `/tmp/atlantis/data/repos/<github username>/atlantis-example/<pull req number>/<env>/<env>/terraform.tfstate.d/<env>/terraform.tfstate`. I accidentally got this due to click the conflict PR (e.g. Plan Failed: This project is currently locked by #1. The locking plan must be applied or discarded before future plans can execute).

**Comment by lkysow** [comment]
ahh okay, let me know if you run into anything else!
