### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by nwalke** [hootsuite/atlantis#98]
Would be awesome to have this support GitLab

**Comment by lkysow** [comment]
Hello All,
I'm excited to let you know that the [latest version of Atlantis](https://github.com/hootsuite/atlantis/releases/tag/v0.2.0) now has GitLab support!

Since we released Atlantis we've been hard at work refactoring and testing. This work has enabled us to integrate GitLab with relative ease.

**GitLab integration is still in Beta.** If any of you would like to try it out and provide feedback that would be much appreciated. We haven't had the chance to try it out with GitLab enterprise for example.

Hope you all can now run Atlantis, and happy Terraforming!

![gitlab2](https://user-images.githubusercontent.com/1034429/32929637-43d9d4be-cb0e-11e7-80d9-7807c91912f0.gif)

**Comment by lkysow** [comment]
@DavidWittman @onoffleftright @jnakatsui @xueshanf @stefan-caraiman @guidob @liuyu @piotrgo @dmaspataud @mNantern @viveleroy @joshuatalb @jakubigla @salemgolemugoo @cristian04 @troehnke @tieum @jamesschafer @rawkode @davekaufman @sidewinder12s @while1eq1 @nalbyuites

Not sure if you get notifications if you just "react" to an issue so tagging you to let you know that GitLab integration is in the latest version of Atlantis now. Would love for some of you to try it out and help work out any issues.

**Comment by rawkode** [comment]
Hi @lkysow, is it possible to change the GitLab server address?

**Comment by lkysow** [comment]
@rawkode yes you can use
```
--gitlab-hostname string         Hostname of your GitLab Enterprise installation. If using gitlab.com, no need to set. (default "gitlab.com")
```
